server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  # --- Descoberta autom√°tica dos containers Docker ---
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Nome do container (api-payments, prometheus, etc)
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container_name

      # Caminho dos arquivos json.log do container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

      # Remove o path original
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      # Reescreve o __path__ apontando para o .json.log
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: "/var/lib/docker/containers/$1/$1-json.log"

    # --- Pipeline para parsear JSON do Node/Pino ---
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            payment: payment
            trace_id: trace_id
            span_id: span_id
      - timestamp:
          source: time
          format: RFC3339Nano
          action_on_failure: skip
